### ISSUE TITLE
Inflated text contains alien bytes  ÿ þ

### ISSUE THREAD

**Issue by beyondgrayzone** [ScottMansfield/nanolog#3]
Text generated from ``` inflate -f src nanolog.txt``` contains alien bytes ( ``` ÿ þ ```) in the very beginning, which is interfering with Windows powershell renderer.

Try this

```
	r := bufio.NewReader(getFileReader("nanolog.txt"))

	var count int
	for {
		count++
		b, _, err := r.ReadLine()
		if err != nil {
			break
		}
		if count == 1 {
			p("FIRST TWO BYTES > ", string(b[0]), string(b[1]), string(b[2]))
		}
		fmt.Println(string(b))
	}
```

**Comment by ScottMansfield** [comment]
Can you give more detail? I'm not sure how those bytes would be in there unless they were put in by the program logging. The command line `inflate -f src nanolog.txt` seems incorrect to me, however I have no experience in Powershell. Does that mean direct stdout to nanolog.txt? The inflate command will output to stdout and you will need to direct it to a file.

**Comment by beyondgrayzone** [comment]
My bad, that cli  in my comment was actually a typo.

[Here is the code](https://gist.github.com/MintyOwl/b8af8be4d1905d0ab11e2948abc5c352). 
Then run
```
inflate -f nano.clog > nano.log
```

Then toggle the two functions in the ```main``` in the demo to see what I mean

**Comment by ScottMansfield** [comment]
I can't reproduce that, unfortunately. I had to edit your file to make it actually write to the file, this is the one I ran: https://gist.github.com/ScottMansfield/1874f78efda62f63655d616cd0ddd766

```
$ go run foo.go
93.311µs

$ ./inflate -f nano.clog > nano.log

$ go run foo.go
FIRST TWO BYTES >  1 4 9

1493703436850061254 Example 0 log this is a string line true
1493703436850088618 Example 1 log this is a string line true
...
```

**Comment by beyondgrayzone** [comment]
Strange. Maybe this is Windows specific thing. If I get time I will investigate for sure.

Thanks for the help.
